# Generated by Django 2.2.4 on 2019-09-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_review_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(null=True, upload_to='outlines/'),
        ),
    ]
