# Generated by Django 2.2.4 on 2019-09-07 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_course_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.FileField(upload_to='syallbus/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
