# Generated by Django 2.2.4 on 2019-09-08 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190908_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='course_code',
            new_name='course',
        ),
    ]
