# Generated by Django 2.2.4 on 2019-09-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190911_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='taken_season',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Summer', 'Summer')], default='Fall', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='taken_year',
            field=models.IntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000)], default='2019'),
        ),
    ]
